services:
  pyram:
    container_name: pyram
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    tty: true
    runtime: nvidia
    environment:
      - DISPLAY
      - XAUTHORITY
      - "QT_X11_NO_MITSHM=1"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    volumes:
      - type: volume
        source: pyram-src
        target: /workspace
      - type: volume
        source: pyram-data
        target: /dados
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: vscode-pyram
        target: /workspace/.vscode

volumes:
  vscode-pyram:
    name: vscode-pyram
    driver: local
    driver_opts:
      device: ../.vscode-pyram
      o: bind
      type: local

  pyram-src:
    name: pyram-src
    driver: local
    driver_opts:
      device: ../pyram
      o: bind
      type: local

  pyram-data:
    name: pyram-data
    driver: local
    driver_opts:
      device: ../datasets
      o: bind
      type: none
